version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5002:5092"  # Clean mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq

  inventory-service:
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    ports:
      - "5003:5281"  # Clean mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5001:5035"  # Clean mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ__URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - user-service
      - inventory-service
